### ISSUE TITLE
Class definition separated into 2 code snippets

### ISSUE THREAD

**Issue by kosist** [dotnet/docs-desktop#65] opened 2020-10-06 20:44 UTC
![image](https://user-images.githubusercontent.com/1911151/95257965-5ce11880-0825-11eb-933b-5fee05699b71.png)

P.S. I've already posted similar issue, so reason is clear - just let me post this issue here, so it would be tracked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92bed672-2ba0-a07e-e18c-e4d0694f6952
* Version Independent ID: 8c72a6e4-09c0-4938-cf6a-75a6c57da047
* Content: [Customize Cells and Columns in DataGridView Control by Extending Their Behavior and Appearance - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/customize-cells-and-columns-in-the-datagrid-by-extending-behavior?view=netframeworkdesktop-4.8#feedback)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/customize-cells-and-columns-in-the-datagrid-by-extending-behavior.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/winforms/controls/customize-cells-and-columns-in-the-datagrid-by-extending-behavior.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2020-10-12 21:04
Duplicate of #53

**Closed by adegeo** 2020-10-12 21:04 UTC
Labels: :books: Area - .NET Framework, :card_file_box: Technology - WinForms, :watch: Not Triaged
