### ISSUE TITLE
Issue with xaml code window

### ISSUE THREAD

**Issue by pomahtik0** [dotnet/docs-desktop#1666] opened 2023-07-05 11:10 UTC
One extra xaml window

![issue1](https://github.com/dotnet/docs-desktop/assets/137159407/c1176985-4a62-4c20-ac12-722c04735768)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e09eb1dd-0897-a1c1-790a-ea372de68e31
* Version Independent ID: e37b562f-bea1-3f6e-22c4-ca7097bdb604
* Content: [How to: Specify the Binding Source - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/data/how-to-specify-the-binding-source?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/data/how-to-specify-the-binding-source.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/data/how-to-specify-the-binding-source.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2023-07-05 17:10
Thank you for reporting this. We have a running list of these articles.

**Comment by adegeo** [comment] 2023-07-05 17:11
Duplicate of #53

**Closed** 2023-07-05 17:11 UTC
Labels: Pri1, duplicate, dotnet-framework/prod, dotnet-wpf/tech
