### ISSUE TITLE
Merge ode blocks for each example?

### ISSUE THREAD

**Issue by jmartens** [dotnet/docs-desktop#1345] opened 2022-04-04 09:08 UTC
Shouldn't both code blocks be one code block instead of splitting them in three code blocks each?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5d311dc-a37a-9001-4159-fd3b17d723bd
* Version Independent ID: f668b554-5467-dc29-371f-a75688789637
* Content: [How to: Use Triggers to Style Selected Items in a ListView - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/how-to-use-triggers-to-style-selected-items-in-a-listview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/how-to-use-triggers-to-style-selected-items-in-a-listview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/how-to-use-triggers-to-style-selected-items-in-a-listview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2022-04-27 17:06
Duplicate of #53

**Closed by adegeo** 2022-04-27 17:06 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-framework/prod, dotnet-wpf/tech
