### ISSUE TITLE
Events and XAML code-behind section and its example

### ISSUE THREAD

**Issue by alpmanyas** [dotnet/docs-desktop#1539] opened 2022-11-29 14:37 UTC
Hello,

Thank you for the great page and the explanations. 

I think the example in the "Events and XAML code-behind" section and its explanation are somehow unconnected. May be the example code or the section is changed. Even the Class Names in the example and the explanation do not match. The explanation includes partial class definition in code behind but there is no partial class definition in code behind of the example. 

Best regards,

Alp

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41391f13-7c61-97ac-e16e-ca1f280d79f6
* Version Independent ID: 12ab183d-74fa-e353-9761-fb5edc553e40
* Content: [XAML overview - WPF .NET](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/xaml/?view=netdesktop-6.0#events-and-xaml-code-behind)
* Content Source: [dotnet-desktop-guide/net/wpf/xaml/index.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/xaml/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2022-12-08 20:01
Duplicate of #1542

**Closed by adegeo** 2022-12-08 20:01 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-wpf/tech, dotnet-desktop/prod
