### ISSUE TITLE
Confusing version details

### ISSUE THREAD

**Issue by selebi-pikwe** [dotnet/docs-desktop#1555] opened 2023-01-10 08:52 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09dfecb3-a787-46d7-226d-b808175736cc
* Version Independent ID: eb4e6812-f48e-2a5d-baae-ad7eb9ef6dc1
* Content: [XAML overview - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/xaml-overview?view=netframeworkdesktop-4.8&viewFallbackFrom=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/xaml-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/xaml-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by selebi-pikwe** [comment] 2023-01-10 08:55
No .NET 5 version available, drops back to Framework 4, but text refers to .NET Core.

**Comment by adegeo** [comment] 2023-01-12 01:11
Duplicate of #1549

**Comment by adegeo** [comment] 2023-01-12 01:12
Hi @selebi-pikwe thanks for opening this issue. These updates will be covered this month as part of the other issue I linked to.

**Closed by adegeo** 2023-01-12 01:11 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-framework/prod, dotnet-wpf/tech
