### ISSUE TITLE
Code snippet in Markup extensions shouldn't be splitted

### ISSUE THREAD

**Issue by KiruyaMomochi** [dotnet/docs-desktop#64] opened 2020-10-04 18:39 UTC
In `Markup extensions` part:
![image](https://user-images.githubusercontent.com/65301509/95024144-d6f19000-06b3-11eb-8afc-f7ae37312646.png)
These code should be a whole snippet instead of 3 split snippets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38c7c924-4a4b-f1b2-5599-997d7a4b30ee
* Version Independent ID: 13ffba97-56e8-c4d4-83ba-4a21d7d0a63a
* Content: [XAML overview - WPF .NET](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/fundamentals/xaml?view=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/wpf/fundamentals/xaml.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/net/wpf/fundamentals/xaml.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2020-10-12 21:05
Duplicate of #53

**Comment by adegeo** [comment] 2020-10-12 21:05
Thank you for reporting this. I've added the article to the list of known articles with this issue,

**Closed by adegeo** 2020-10-12 21:05 UTC
Labels: :books: Area - .NET, :card_file_box: Technology - WPF, :watch: Not Triaged
