### ISSUE TITLE
Creating a Composite 

### ISSUE THREAD

**Issue by ErickTreetops** [dotnet/docs-desktop#1537] opened 2022-11-21 10:00 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7614753f-afb5-c605-0998-59083ee38baf
* Version Independent ID: 6a567f8b-06e4-ac91-f352-636431540047
* Content: [Develop a Composite Control - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/developing-a-composite-windows-forms-control?source=recommendations&view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/developing-a-composite-windows-forms-control.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/developing-a-composite-windows-forms-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2022-11-21 17:45
Duplicate of #1538

**Closed by adegeo** 2022-11-21 17:45 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-framework/prod, dotnet-winforms/tech
