### ISSUE TITLE
Long and confusing sentence

### ISSUE THREAD

**Issue by redcurry** [dotnet/docs-desktop#1527] opened 2022-10-27 23:00 UTC
This sentence:

> The keys of the key-value pairs are x:Uid values that are placed by the developer in the original UI after the localizer begins localizing, you can merge the development change with the already completed localization work so that minimal translation work is lost.

is very long and confusing, and I'm not sure what it's trying to say.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7dc952bd-fed7-6cff-e3ae-7ab73eebde02
* Version Independent ID: 9bca4403-30cd-4442-9e1e-765d4a1c4df9
* Content: [Globalization and localization overview - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/wpf-globalization-and-localization-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/wpf-globalization-and-localization-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/wpf-globalization-and-localization-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 169358](https://dev.azure.com/msft-skilling/Content/_workitems/edit/169358)

**Comment by adegeo** [comment] 2023-10-11 16:45
A year later... doh! Anyway, thank you for filing this. I'll get it fixed

**Comment by adegeo** [comment] 2023-10-18 20:36
Ah!!! This was caused by an error in our migration script, as documented in #1597. This was fixed in August by #1688

**Closed by adegeo** 2023-10-18 20:36 UTC
Labels: :watch: Not Triaged, Pri3, dotnet-framework/prod, dotnet-wpf/tech, :pushpin: seQUESTered
