### ISSUE TITLE
The text erroneously references elements not found in the examples

### ISSUE THREAD

**Issue by BruceHaley** [dotnet/docs-desktop#1557] opened 2023-01-15 02:36 UTC
The following wording references elements it erroneously claims are shown in the examples:

"Notice that the code-behind file uses the CLR namespace ExampleNamespace and declares ExamplePage as a partial class within that namespace. This parallels the x:Class attribute value of ExampleNamespace.ExamplePage that was provided in the markup root."

There is neither "ExampleNamespace" nor "ExamplePage" shown anywhere in the examples. (Possibly those things were deleted from the examples, but the text was not updated to match?)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41391f13-7c61-97ac-e16e-ca1f280d79f6
* Version Independent ID: 12ab183d-74fa-e353-9761-fb5edc553e40
* Content: [XAML overview - WPF .NET](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/xaml/?view=netdesktop-6.0)
* Content Source: [dotnet-desktop-guide/net/wpf/xaml/index.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/xaml/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2023-03-15 19:37
Hi @BruceHaley sorry for the delay of getting back to you. It looks like I fixed this in a different bug about 15 days after you opened this one. Sorry for the confusion!

**Comment by adegeo** [comment] 2023-03-15 19:38
Duplicate of #1542

**Closed by adegeo** 2023-03-15 19:38 UTC
Labels: Pri1, doc-bug, dotnet-wpf/tech, dotnet-desktop/prod
