### ISSUE TITLE
Accidental extra code block

### ISSUE THREAD

**Issue by BakuPlayz** [dotnet/docs-desktop#1351] opened 2022-04-11 08:02 UTC
The code block example on the site is accidentally split up into two.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 713fc9ca-506f-f1af-b79b-85833d892454
* Version Independent ID: 34871a66-3028-4913-755e-ab90eb9e2b89
* Content: [How to: Set Up Notification of Binding Updates - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/data/how-to-set-up-notification-of-binding-updates?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/data/how-to-set-up-notification-of-binding-updates.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/data/how-to-set-up-notification-of-binding-updates.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2022-04-11 17:34
Duplicate of #53

**Closed by adegeo** 2022-04-11 17:34 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-framework/prod, dotnet-wpf/tech
