### ISSUE TITLE
Code example split in two

### ISSUE THREAD

**Issue by HankiDesign** [dotnet/docs-desktop#217] opened 2021-03-01 18:52 UTC
**Issue description**

The code block in the [How to: Set Up Notification of Binding Updates](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/data/how-to-set-up-notification-of-binding-updates?view=netframeworkdesktop-4.8) article is split in two, as can be seen in the screenshot below:

![image](https://user-images.githubusercontent.com/1816448/109544202-f14b6080-7acf-11eb-9d13-ded5f5790863.png)

**.NET or .NET Framework**

Check the .NET target framework(s) being used, and include the version number(s). Put an `x` between the `[ ]` to check it.

- [ ] .NET (5 or Core)
- [X] .NET Framework

**Technology**

Check the .NET target framework(s) being used, and include the version number(s). Put an `x` between the `[ ]` to check it.

- [X] WPF
- [ ] Windows Forms

**.NET information**

If using the .NET SDK or .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

**Comment by adegeo** [comment] 2021-03-03 22:30
Thank you for reporting this. I have a running list at #53

**Comment by adegeo** [comment] 2021-03-03 22:30
Duplicate of #53

**Closed by adegeo** 2021-03-03 22:30 UTC
Labels: :watch: Not Triaged, Pri3
